language: node_js

node_js:
  - "10"

cache:
  directories:
    - "node_modules"
    - "$HOME/.sonar/cache"

addons:
  sonarcloud:
    organization: "data-provider"
    branch:
      name: "$TRAVIS_CURRENT_BRANCH"

script:
  - npm run lint
  - npm run test:mocks
  - npm run build
  - npm run coveralls
  - 'if [ -n "$SONAR_TOKEN" ]; then sonar-scanner -Dsonar.login=${SONAR_TOKEN}; fi'

deploy:
  provider: npm
  email: "javier.brea@gmail.com"
  api_key: "$NPM_TOKEN"
  on:
    tags: true
  skip_cleanup: true
